{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import fastai; fastai.__version__\n",
    "from fastai.vision import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys; sys.path.append(\"../dev\")\n",
    "from local.script import run_command"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[PosixPath('experiment_exports/experiment1')]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "EXPORT_PATH = Path(\"./experiment_exports/\");EXPORT_PATH.ls()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[PosixPath('experiment_exports/experiment1/training_log.csv'),\n",
       " PosixPath('experiment_exports/experiment1/stderr.log'),\n",
       " PosixPath('experiment_exports/experiment1/tmp'),\n",
       " PosixPath('experiment_exports/experiment1/models')]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "i = 1\n",
    "EXP_PATH = (EXPORT_PATH/f\"experiment{i}\"); EXP_PATH.ls()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>epoch</th>\n",
       "      <th>train_loss</th>\n",
       "      <th>valid_loss</th>\n",
       "      <th>dice</th>\n",
       "      <th>time</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.787115</td>\n",
       "      <td>13:46</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>epoch</td>\n",
       "      <td>train_loss</td>\n",
       "      <td>valid_loss</td>\n",
       "      <td>dice</td>\n",
       "      <td>time</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.787115</td>\n",
       "      <td>14:24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>epoch</td>\n",
       "      <td>train_loss</td>\n",
       "      <td>valid_loss</td>\n",
       "      <td>dice</td>\n",
       "      <td>time</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.787115</td>\n",
       "      <td>13:43</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   epoch  train_loss  valid_loss      dice   time\n",
       "0      0         NaN         NaN  0.787115  13:46\n",
       "1  epoch  train_loss  valid_loss      dice   time\n",
       "2      0         NaN         NaN  0.787115  14:24\n",
       "3  epoch  train_loss  valid_loss      dice   time\n",
       "4      0         NaN         NaN  0.787115  13:43"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.read_csv(EXPORT_PATH/f\"experiment{i}/training_log.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "scrolled": false
   },
   "outputs": [],
   "source": [
    "log = json.loads(open(EXPORT_PATH/f\"experiment{i}/stderr.log\").read())[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "To use this log_lamb_rs, please run 'pip install tensorboardx'. Also you must have Tensorboard running to see results\n",
      "Print args here: \n",
      "Training with arch: <function resnet34 at 0x7f9b8b62fd08>\n",
      "Tracking metric: <function dice at 0x7f9b8cbe4ae8>\n",
      "Training with loss: FlattenedLoss of CrossEntropyLoss()\n",
      "Starting training with max_lr: 0.003\n",
      "Training with transfer learning\n",
      "Initializing self.best\n",
      "Initializing self.best\n",
      "Initializing self.best\n",
      "Initializing self.best\n",
      "Initializing self.best\n",
      "epoch     train_loss  valid_loss  dice      time    \n",
      "Initializing self.best\n",
      "Initializing self.best\n",
      "0         nan         nan         0.787115  13:45     \n",
      "Better model found at epoch 0 with dice value: 0.7871145009994507.\n",
      "Total time: 13:45\n",
      "Total time: 13:45\n",
      "Total time: 13:45\n",
      "Total time: 13:45\n",
      "Total time: 13:45\n",
      "Total time: 13:45\n",
      "Total time: 13:46\n",
      "epoch     train_loss  valid_loss  dice      time    \n",
      "0         nan         nan         0.787115  14:24     \n",
      "Total time: 14:24\n",
      "Total time: 14:24\n",
      "Total time: 14:24\n",
      "Total time: 14:24\n",
      "Total time: 14:24\n",
      "Total time: 14:24\n",
      "Total time: 14:24\n",
      "epoch     train_loss  valid_loss  dice      time    \n",
      "Total time: 13:43\n",
      "0         nan         nan         0.787115  13:43     \n",
      "Total time: 13:43\n",
      "Total time: 13:43\n",
      "Total time: 13:43\n",
      "Total time: 13:43\n",
      "Generating Raw Predictions for Valid...\n",
      "Total time: 13:43\n",
      "Total time: 13:43\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(log['stdout'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 7; 10.73 GiB total capacity; 8.39 GiB already allocated; 341.56 MiB free; 1.23 GiB cached)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 3; 10.73 GiB total capacity; 8.38 GiB already allocated; 339.56 MiB free; 1.24 GiB cached)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 5; 10.73 GiB total capacity; 8.39 GiB already allocated; 341.56 MiB free; 1.23 GiB cached)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 2; 10.73 GiB total capacity; 8.39 GiB already allocated; 345.56 MiB free; 1.23 GiB cached)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 4; 10.73 GiB total capacity; 8.39 GiB already allocated; 333.56 MiB free; 1.23 GiB cached)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 0; 10.73 GiB total capacity; 8.37 GiB already allocated; 351.19 MiB free; 1.23 GiB cached)\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 37, in <module>\n",
      "    gpu:Param(\"GPU to run on, can handle multi gpu\", str)=None):\n",
      "  File \"/home/turgutluk/fastai/fastai/script.py\", line 40, in call_parse\n",
      "    func(**args.__dict__)\n",
      "  File \"/home/turgutluk/git/fast-kaggle/dev/segmentation_training.py\", line 133, in main\n",
      "    preds, targs = learn.get_preds(getattr(DatasetType, dtype))\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 339, in get_preds\n",
      "    activ=activ, loss_func=lf, n_batch=n_batch, pbar=pbar)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 44, in get_preds\n",
      "    zip(*validate(model, dl, cb_handler=cb_handler, pbar=pbar, average=False, n_batch=n_batch))]\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 59, in validate\n",
      "    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)\n",
      "  File \"/home/turgutluk/fastai/fastai/basic_train.py\", line 26, in loss_batch\n",
      "    out = model(*xb)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/fastai/fastai/layers.py\", line 136, in forward\n",
      "    nres = l(res)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/container.py\", line 92, in forward\n",
      "    input = module(input)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 493, in __call__\n",
      "    result = self.forward(*input, **kwargs)\n",
      "  File \"/home/turgutluk/.conda/envs/my_fastai/lib/python3.7/site-packages/torch/nn/modules/conv.py\", line 338, in forward\n",
      "    self.padding, self.dilation, self.groups)\n",
      "RuntimeError: CUDA out of memory. Tried to allocate 424.00 MiB (GPU 1; 10.73 GiB total capacity; 8.40 GiB already allocated; 343.56 MiB free; 1.22 GiB cached)\n",
      "\n"
     ]
    }
   ],
   "source": [
    "print(log['stderr'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
